name: Spotify Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install system deps
        run: sudo apt-get install -y ffmpeg

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: python bot.py
